game:
  strategy:
    numberOfTurnsToAnalyze: 20

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://db:3306/game
    username: root
    password: root
    validationQuery: SELECT 1

  jpa:
    show-sql: true
    generate-ddl: true
    ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect