package service.strategy;

import model.Move;
import model.Result;
import model.Turn;
import service.strategy.draw.DrawMoveResolver;

import java.util.LinkedList;

import static service.result.ResultDeterminant.winCombinations;

/**
 * This strategy assumes that player DOES KNOW about the result of scientific research
 * described in the based interface. This means that every time players losses the server
 * assumes that player knows how @ScientificMoveStrategy works and will change to move on the
 * next turn so beat the move generated by @ScientificMoveStrategy.
 * For example, if player lost with combination (PAPER, ROCK) on the next turn @ScientificMoveStrategy
 * will assume the player chooses SCISSORS, so generates ROCK. But if player is aware of this
 * strategy he will choose PAPER, so server should use SCISSORS.
 */
public class ScientificRevertedMoveStrategy implements MoveStrategy {

    private final DrawMoveResolver drawMoveResolver;

    public ScientificRevertedMoveStrategy(DrawMoveResolver drawMoveResolver) {
        this.drawMoveResolver = drawMoveResolver;
    }

    /**
     * According to scientific research ROCK is the most popular move as a first one in the game,
     * so by default server will generate PAPER.
     */
    @Override
    public Move nextMove(LinkedList<Turn> previousTurns) {
        if (previousTurns.isEmpty()) {
            return Move.PAPER;
        }

        Turn lastTurn = previousTurns.getLast();
        if (lastTurn.getResult().equals(Result.DRAW)) {
            return drawMoveResolver.moveAfterDraw(previousTurns);
        } else if (lastTurn.getResult().equals(Result.LOSS)) {
            Move scientificMoveStrategy = winCombinations.get(winCombinations.get(lastTurn.getServerMove()));
            Move expectedNextPlayerMove = winCombinations.get(scientificMoveStrategy);
            return winCombinations.get(expectedNextPlayerMove);
        } else {
            Move scientificMoveStrategy = winCombinations.get(lastTurn.getPlayerMove());
            Move expectedNextPlayerMove = winCombinations.get(scientificMoveStrategy);
            return winCombinations.get(expectedNextPlayerMove);
        }
    }
}